server:
  port: 8082

spring:
  profiles:
    active: dev #默认为开发环境
  thymeleaf: #thymeleaf
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
    cache: false
  devtools: #热部署
    restart:
      enabled: true
      additional-paths: src/mian/java
      exclude: static

mybatis:
  mapper-locations:
    -classpath: mapper/*.xml
    -classpath*: com/**/mapper/*.xml


logging:
  level:
    root: info #日志配置DEBUG，INFO，WARN，REEOR
    com.blog: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

