server:
  port: 8082

spring:
  profiles:
    active: dev #默认为开发环境
  thymeleaf: #thymeleaf
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
    cache: false
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true
      file-size-threshold: 200KB
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    ssl: false


file:
  upload: /Users/suao/Desktop/代码/myblog/src/main/resources/upload
  uploadPic : /Users/suao/Desktop/代码/myblog/src/main/resources/static/uploadImage

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.blog.mapper


logging:
  level:
    root: info #日志配置DEBUG，INFO，WARN，REEOR
    com.blog: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

